import "server-only";
import type { T } from "@/lib/translator";
import type { ProformaBuilderStrings } from "@/components/ProformaBuilder";

/** Builds the translated strings object the client-side ProformaBuilder
 * needs, shared by both the create page and the edit page so the two never
 * drift out of sync. */
export function buildProformaBuilderStrings(t: T): ProformaBuilderStrings {
  return {
    sectionClient: t("proforma.section_client"),
    clientNamePh: t("proforma.client_name_ph"),
    clientEmailPh: t("proforma.client_email_ph"),
    clientCompanyPh: t("proforma.client_company_ph"),
    clientPhonePh: t("proforma.client_phone_ph"),
    clientCityPh: t("proforma.client_city_ph"),
    clientCountryPh: t("proforma.client_country_ph"),
    unitSqm: t("proforma.unit_sqm"),
    unitSqf: t("proforma.unit_sqf"),
    stoneItems: t("proforma.stone_items"),
    itemStoneLabel: t("proforma.item_stone_label"),
    itemGradeLabel: t("proforma.item_grade_label"),
    itemCategoryLabel: t("proforma.item_category_label"),
    itemSizeLabel: t("proforma.item_size_label"),
    itemThicknessLabel: t("proforma.item_thickness_label"),
    itemFinishLabel: t("proforma.item_finish_label"),
    selectStonePh: t("proforma.select_stone_ph"),
    selectCategoryPh: t("proforma.select_category_ph"),
    selectSizePh: t("proforma.select_size_ph"),
    customSizeLabel: t("proforma.custom_size_label"),
    widthCmLabel: t("proforma.width_cm_label"),
    heightCmLabel: t("proforma.height_cm_label"),
    areaPerPieceTemplate: t("proforma.area_per_piece"),
    totalAreaNeededTemplate: t("proforma.total_area_needed"),
    totalAreaNeededPh: t("proforma.total_area_needed_ph"),
    unitPriceLabel: t("proforma.unit_price_label"),
    areaLabel: t("proforma.area_label"),
    lineTotalLabel: t("proforma.line_total_label"),
    selectPrompt: t("proforma.select_prompt"),
    removeItemAria: t("proforma.remove_item_aria"),
    addItem: t("proforma.add_item"),
    incotermPaymentLabel: t("proforma.incoterm_label"),
    incotermLabel: t("proforma.incoterm"),
    incotermDdpNote: t("proforma.incoterm_ddp_note"),
    incotermBuyerLabel: t("proforma.incoterm_buyer_label"),
    incotermSellerLabel: t("proforma.incoterm_seller_label"),
    incotermRiskLabel: t("proforma.incoterm_risk_label"),
    paymentTermLabel: t("proforma.payment_term"),
    shippingLabel: t("proforma.shipping_label"),
    destinationCountryLabel: t("proforma.destination_country"),
    selectGenericPh: t("proforma.select_generic_ph"),
    destinationPortLabel: t("proforma.destination_port"),
    selectCountryFirst: t("proforma.select_country_first"),
    zoneInfoTemplate: t("proforma.zone_info"),
    notesForTeamLabel: t("proforma.notes_for_team_label"),
    notesForTeamPh: t("proforma.notes_for_team_ph"),
    sectionSummary: t("proforma.section_summary"),
    totalArea: t("proforma.total_area"),
    goodsSubtotal: t("proforma.goods_subtotal"),
    containers20ft: t("proforma.containers_20ft"),
    grandTotalWithIncotermTemplate: t("proforma.grand_total_with_incoterm"),
    saving: t("proforma.saving"),
    createBtn: t("proforma.create_btn"),
    saveChangesBtn: t("proforma.save_changes_btn"),
    errClientRequired: t("proforma.err_client_required"),
    errItemsRequired: t("proforma.err_items_required"),
    errCountryRequired: t("proforma.err_country_required"),
    errIncotermRequired: t("proforma.err_incoterm_required"),
    errPaymentRequired: t("proforma.err_payment_required"),
    errSaveFailed: t("proforma.err_save_failed"),
    costLabels: {
      packing: t("cost.packing"),
      inland: t("cost.inland"),
      customs: t("cost.customs"),
      loading: t("cost.loading"),
      freight: t("cost.freight"),
      insurance: t("cost.insurance"),
      import: t("cost.import"),
      delivery: t("cost.delivery"),
    },
  };
}
